### ISSUE TITLE
Include icon preview in README

### ISSUE THREAD

**Issue by niyasc** [solus-project/solus-icon-theme#10]
I understand that, this theme is on it's early stage of development. However, it would be cool if icon preview is included in README file.

**Comment by snwh** [comment]
I don't think that's necessary.

**Comment by ikeydoherty** [comment]
@niyasc - "Solus" icon theme. Let's worry about ourselves first before we take third party requests :)

**Comment by snwh** [comment]
I just didn't want to bog down the README with unnecessary code. Just because markdown can, doesn't mean it should. ;)
